// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A chatbot that answers frequently asked questions about the platform.
 *
 * - chatbot - A function that answers user questions about the platform.
 * - ChatbotInput - The input type for the chatbot function.
 * - ChatbotOutput - The return type for the chatbot function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const ChatbotInputSchema = z.object({
  question: z.string().describe('The user question.'),
});
export type ChatbotInput = z.infer<typeof ChatbotInputSchema>;

const ChatbotOutputSchema = z.object({
  answer: z.string().describe('The answer to the user question.'),
});
export type ChatbotOutput = z.infer<typeof ChatbotOutputSchema>;

export async function chatbot(input: ChatbotInput): Promise<ChatbotOutput> {
  return chatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'faqChatbotPrompt',
  input: {
    schema: z.object({
      question: z.string().describe('The user question.'),
    }),
  },
  output: {
    schema: z.object({
      answer: z.string().describe('The answer to the user question.'),
    }),
  },
  prompt: `You are a chatbot assistant for the NyeriConnect platform. Answer the user's question about the platform.

Question: {{{question}}}

Answer: `,
});

const chatbotFlow = ai.defineFlow<
  typeof ChatbotInputSchema,
  typeof ChatbotOutputSchema
>(
  {
    name: 'chatbotFlow',
    inputSchema: ChatbotInputSchema,
    outputSchema: ChatbotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
