// src/components/icons.ts

import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  BellOff,
  Check,
  ChevronsUpDown,
  Circle,
  CircleDollarSign,
  Copy,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  HelpCircle,
  Home,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  Sun,
  Tag,
  Trash,
  User,
  Users,
  X,
  Workflow,
  Image,
  Phone,
  Info,
  Key,
  Inbox,      // Was already here
  Bell,       // Was already here
  Bot,
  MapPin,
  LayoutGrid,
  Package,    // Added for packageSearch replacement
  AlertCircle,// Added
  DollarSign, // Added
  Receipt,    // Added
  Archive,    // Added as an alternative for listX if needed elsewhere
} from "lucide-react";

// Re-export all icons for easier import
export const Icons = {
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bellOff: BellOff,
  check: Check,
  chevronsUpDown: ChevronsUpDown,
  circle: Circle,
  circleDollarSign: CircleDollarSign,
  copy: Copy,
  edit: Edit,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  helpCircle: HelpCircle,
  home: Home,
  loader2: Loader2,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  menu: Menu,
  messageSquare: MessageSquare,
  moon: Moon,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  shield: Shield,
  shieldAlert: ShieldAlert,
  sun: Sun,
  tag: Tag,
  trash: Trash,
  user: User,
  users: Users,
  x: X,
  workflow: Workflow,
  image: Image,
  phone: Phone,
  info: Info,
  key: Key,
  inbox: Inbox,
  bell: Bell,
  bot: Bot,
  mapPin: MapPin,
  layoutGrid: LayoutGrid,
  package: Package,      // Added export
  alertCircle: AlertCircle, // Added export
  dollarSign: DollarSign, // Added export
  receipt: Receipt,      // Added export
  archive: Archive,        // Added export (used for listX replacement)
  spinner: Loader2,
};
