// src/components/icons.ts

import {
  AlertTriangle,
  ArrowLeft, // Added for back buttons
  ArrowRight,
  BellOff,
  Check,
  ChevronsUpDown,
  Circle,
  CircleDollarSign,
  Copy,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  HelpCircle,
  Home,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu, // Added Menu icon
  MessageSquare,
  Moon,
  Plus,
  PlusCircle,
  Search,
  Send,
  Server,
  Settings,
  Share2,
  Shield,
  Sun,
  Tag,
  Trash,
  User,
  X,
  Workflow,
  Image,
  Phone,
  Info,
  Key,
  Inbox,
  Bell,
  Bot,
  MapPin // Added MapPin
} from "lucide-react";

// Re-export all icons for easier import
export const Icons = {
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bellOff: BellOff,
  check: Check,
  chevronsUpDown: ChevronsUpDown,
  circle: Circle,
  circleDollarSign: CircleDollarSign,
  copy: Copy,
  edit: Edit,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  file: File,
  helpCircle: HelpCircle,
  home: Home,
  loader2: Loader2,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  menu: Menu, // Added Menu icon export
  messageSquare: MessageSquare,
  moon: Moon,
  plus: Plus,
  plusCircle: PlusCircle,
  search: Search,
  send: Send,
  server: Server,
  settings: Settings,
  share2: Share2,
  shield: Shield,
  sun: Sun,
  tag: Tag,
  trash: Trash,
  user: User,
  x: X,
  workflow: Workflow,
  image: Image,
  phone: Phone,
  info: Info,
  key: Key,
  inbox: Inbox,
  bell: Bell,
  bot: Bot,
  mapPin: MapPin, 
  // Add spinner alias for convenience if needed
  spinner: Loader2, 
};
